---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install: cd tests

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version
  - ansible-galaxy install -r roles.txt

script:
  # Basic role syntax check
  - ansible-playbook test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
